# Generated by Django 2.2.16 on 2023-02-28 08:12

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20230228_0809'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_start_date',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='can not subscribe to yourself'),
        ),
    ]
